export type UserRole = "student" | "institution" | "company" | "admin";
export type DegreeType = "licenta" | "master" | "doctorat" | "bacalaureat" | "bacalaureat_licenta";
export type SkillLevel = "incepator" | "intermediar" | "avansat";
export interface Profile { id: string; created_at: string; updated_at: string; email: string; full_name: string; role: UserRole; headline: string | null; bio: string | null; avatar_url: string | null; background_url: string | null; location: string | null; followers_count: number; qr_code_slug: string | null; }
export interface Education { id: string; profile_id: string; institution_name: string; degree: DegreeType; field_of_study: string; start_date: string; end_date: string | null; is_current: boolean; }
export interface Experience { id: string; profile_id: string; company_name: string; position_title: string; location: string | null; work_mode: "onsite" | "hybrid" | "remote" | null; job_type: "fulltime" | "parttime" | "contract" | "volunteer" | "temporary" | "internship" | "other" | null; start_date: string; end_date: string | null; is_current: boolean; description: string | null; }
export interface Project { id: string; profile_id: string; title: string; description: string | null; github_url: string | null; live_demo_url: string | null; technologies: string[]; image_url: string | null; }
export interface Skill { id: string; profile_id: string; name: string; level: SkillLevel; }
export interface RecommendationRequest { id: string; profile_id: string; recipient_name: string; recipient_email: string; relationship: string | null; message: string | null; status: "draft" | "requested" | "received" | "declined"; recommendation_text: string | null; created_at: string; updated_at: string; }
export interface OnboardingData { fullName: string; headline: string; bio: string; location: string; avatarUrl: string | null; educations: Omit<Education, "id" | "profile_id">[]; experiences: Omit<Experience, "id" | "profile_id">[]; skills: Omit<Skill, "id" | "profile_id">[]; projects: Omit<Project, "id" | "profile_id">[]; }
